config/routes.rb
Rails.application.routes.draw do
  devise_for :administrator

  namespace :admin do
    root "projects#index"

    resources :descriptions
    resources :features, param: :name
    resources :projects, param: :name
    resources :plans
    resources :packages, param: :name
    resources :technologies
    resources :technology_types
    resources :technology_types
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#home"

  get "feature/:name" => "features#show", as: :feature
  get "features" => "features#index", as: :features
  get "project/:name" => "projects#show", as: :project
  get "projects" => "projects#index", as: :projects
  get "technology/:name" => "technologies#show", as: :technology
  get "packages" => "packages#index", as: :packages
  get "dashboard" => "dashboard#dashboard", as: :dashboard
  get "booking-application-features" => 'booking_application#features', as: :booking_application_features

  # feed for learning spanish
  get "/spanish-feed" => "spanish#feed", defaults: {format: :json}

  draw :quiz
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :project
end

app/models/feature.rb
class Feature < ApplicationRecord
  # belongs to
  belongs_to :project
  # has many
  has_many :technology_groups, as: :technology_groupable, dependent: :destroy
  # validation
  validates_uniqueness_of :name

  # TODO Add star attribute.

  def to_param
    name
  end

  def technologies
    technology_groups.map { |tg| tg.technology }
  end

  def technology_names
    technology_groups.map { |tg| tg.technology.name }
  end
end

app/models/flash_card.rb
class FlashCard < ApplicationRecord
  belongs_to :flash_card_category

  def score
    total_attempts = correct + incorrect

    return 0 if total_attempts.zero?

    # calculate the basic score
    basic_score = (correct.to_f / total_attempts) * 100

    # get the number of days since last updated
    days_since_update = (Time.current - updated_at) / (60 * 60 * 24)

    # calculate the time penalty (0 to 1, where 0 means it was updated today and 1 means it was updated more than 30 days ago)
    time_penalty = [days_since_update / 30.0, 1].min

    # apply the time penalty to the score
    final_score = basic_score * (1 - time_penalty)

    final_score.round(2)
  end
end

app/models/flash_card_category.rb
class FlashCardCategory < ApplicationRecord
  acts_as_tree
  has_many :flash_cards

  def to_param
    name
  end

  def total_flash_cards_count
    flash_cards_count = flash_cards.count

    children.each do |child|
      flash_cards_count += child.total_flash_cards_count
    end

    flash_cards_count
  end

  def total_correct_answers_count
    correct_answers_count = flash_cards.sum(:correct)

    children.each do |child|
      correct_answers_count += child.total_correct_answers_count
    end

    correct_answers_count
  end

  def total_incorrect_answers_count
    incorrect_answers_count = flash_cards.sum(:incorrect)

    children.each do |child|
      incorrect_answers_count += child.total_incorrect_answers_count
    end

    incorrect_answers_count
  end

  def score
    total_flash_cards = flash_cards.count

    return 0 if total_flash_cards.zero?

    total_score = flash_cards.sum do |flash_card|
      flash_card.score.to_f
    end

    average_score = total_score / total_flash_cards
    average_score.round(2)
  end


  def total_flash_cards
    flash_cards.count
  end

  def correct_flash_cards
    flash_cards.sum(&:correct)
  end

  def incorrect_flash_cards
    flash_cards.sum(&:incorrect)
  end

  def self.ordered_by_score
    all.sort_by(&:score).reverse
  end

  def self.root_categories_ordered_by_score
    roots.sort_by(&:score).reverse
  end
end

app/models/package.rb
class Package < ApplicationRecord
  # belongs to
  belongs_to :technology
  # has many
  has_many :technology_groups, as: :technology_groupable, dependent: :destroy
  has_many :package_groups, as: :package_groupable, dependent: :destroy
  # validates
  validates_uniqueness_of :name

  def to_param
    name
  end
end

app/models/package_group.rb
class PackageGroup < ApplicationRecord
  belongs_to :package_groupable, polymorphic: true
  belongs_to :package
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  # has many
  has_many :features
  has_many :technology_groups, as: :technology_groupable, dependent: :destroy
  has_many :technologies, through: :technology_groups
  has_many :package_groups, as: :package_groupable, dependent: :destroy
  has_many :packages, through: :package_groups
  has_many :plans
  has_many :descriptions
  # validation
  validates_uniqueness_of :name
  # scopes
  scope :all_visible, -> { where(visible: true).order(:order) }

  # TODO Add packages to a project

  def to_param
    name
  end

  def completed_features
    features.where(completed: true)
  end

  def features_left_to_implement
    features.where(completed: false)
  end

  def technology_names
    technologies.map(&:name)
  end

  def package_names
    packages.map(&:name)
  end

  def theme_colour_first
    theme_colours.split(",").first
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  # has many
  has_many :technology_groups
  has_many :packages
  # belongs to
  belongs_to :technology_type
  # validations
  validates_uniqueness_of :name


  def projects
    find_technolgoy_group_type("Project")
  end

  def features
    find_technolgoy_group_type("Feature")
  end

  def find_technolgoy_group_type(type)
    technology_groups.all.map do |tg|
      if tg.technology_groupable.class.name == type
        tg.technology_groupable
      end
    end.compact
  end
end

app/models/technology_group.rb
class TechnologyGroup < ApplicationRecord
  # should be able to belong to project or features (polymorphic)
  belongs_to :technology_groupable, polymorphic: true
  belongs_to :technology
end

app/models/technology_type.rb
class TechnologyType < ApplicationRecord
  has_many :technologies
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "blank_layout"

  def dashboard
    @projects = Project.all
  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :find_feature, only: %i[show]

  def show
    @technologies_used = @feature.technology_names
  end

  def index
    @features = Feature.all
  end

  private

  def find_feature
    @feature = Feature.find_by(name: params[:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home
      @projects = Project.all_visible
      @features = Feature.all[0..3]
    end

    def beeper
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def index
    @packages = Package.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show]

  def show
    # TODO add attribute to project visible: boolean
    @features = Feature.all
    @technologies_used = @project.technology_names
  end

  def index
    @projects = Project.all.order(:order)
  end

  private

  def set_project
    @project = Project.find_by(name: params[:name])
  end
end

app/controllers/spanish_controller.rb
class SpanishController < ApplicationController
  before_action :set_headers

  def feed
  end

  protected

  def set_headers
    response.headers['Access-Control-Allow-Origin'] = '*'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/shared/_feature.html.erb
<%= link_to feature_path(feature), class: "project-sectionContainer white-container" do %>
  <h6><%= feature.name %></h6>
  <p><%= feature.description %></p>
  <p><%= feature.project.name %></p>
  <% feature.technologies.each do |technology| %>
    <%= image_tag technology.icon, class: "feature-icon" %>
  <% end %>
  <b><%= feature.completed ? "Completed" : "In progress" %></b>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="flashMessage-container alert flashMessage-<%= type %> alert-dismissible fade show" role="alert">
    <div class="px-3">
      <h5 class="m-0"><b><%= type %></b></h5>
      <p class="m-0"><%= msg %></p>
    </div>
    <div>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-iconsContainer">
    <%= link_to "https://www.facebook.com/fordswebdevelopment", target: "_blank", class: "footer-icon" do %>
      <%= image_tag "icons/facebook.png" %>
    <% end %>
    <%= link_to "https://www.instagram.com/fordsdevelopment_projects/", target: "_blank", class: "footer-icon" do %>
      <%= image_tag "icons/instagram.png" %>
    <% end %>
     <%= link_to "https://twitter.com/alexfordsdev", target: "_blank", class: "footer-icon" do %>
      <%= image_tag "icons/twitter.png" %>
    <% end %>
  </div>
  <div class="footer-linksContainer">
    <%= link_to "Home", root_path %>
    <% if Project.all.any? %>
      <%= link_to "Projects", project_path(Project.first) %>
    <% end %>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<div class="navigation-linksContainer">
  <%= link_to projects_path, class: "nav-link" do %>
    <%= image_tag "icons/outline/projects.png" %>
    <span>Projects</span>
  <% end %>
  <%= link_to features_path, class: "nav-link" do %>
    <%= image_tag "icons/outline/feature_branch.png" %>
    <span>Features</span>
  <% end %>
  <%= link_to packages_path, class: "nav-link" do %>
    <%= image_tag "icons/outline/package.png" %>
    <span>Packages</span>
  <% end %>
</div>
<nav class="navigation-container">
  <div class="navigation-wrapper">
    <% @technologies.each do |technology| %>
      <%= link_to technology_path(technology.name), class: "nav-iconLink" do %>
        <%= image_tag technology.icon, class: "nav-icon #{"nav-icon-active" if technology.name == params[:name] || @technologies_used.include?(technology.name)}" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_package.html.erb
<div class="technology-packageWrapper white-container">
  <h6><%= package.name %></h6>
  <p><%= package.description %></p>
  <%= image_tag package&.technology&.icon, class: "feature-icon" %>
</div>

app/views/shared/_project.html.erb
<%= link_to project_path(project), class: "projectCard-container white-container", style: "background-color:#{project.theme_colour_first}" do %>
  <h6><%= project.name %></h6>
  <p><%= project.sub_title %></p>
  <% if project.logo %>
    <%= image_tag project.logo, class: "projectCard-logo" %>
  <% end %>
<% end %>

app/views/shared/_technology.html.erb
<%= link_to technology_path(technology.name), class: "technology-container white-container", data: {"aos-center": "slow"} do %>
  <%# TODO Add for screen readers %>
  <p class="text-secondary"><b><%= technology.name.capitalize %></b></p>
  <div class="technology-iconContainer">
    <%= image_tag technology.icon, class: "project-icon" %>
  </div>
<% end %>