config/routes.rb
Rails.application.routes.draw do
  devise_for :administrator

  namespace :admin do
    root "projects#index"

    resources :descriptions
    resources :features, param: :name
    resources :projects, param: :name
    resources :plans
    resources :packages, param: :name
    resources :technologies
    resources :technology_types
    resources :technology_types
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#home"

  get "feature/:name" => "features#show", as: :feature
  get "features" => "features#index", as: :features
  get "project/:name" => "projects#show", as: :project
  get "projects" => "projects#index", as: :projects
  get "technology/:name" => "technologies#show", as: :technology
  get "packages" => "packages#index", as: :packages
  get "dashboard" => "dashboard#dashboard", as: :dashboard
  get "booking-application-features" => 'booking_application#features', as: :booking_application_features

  # feed for learning spanish
  get "/spanish-feed" => "spanish#feed", defaults: {format: :json}

  draw :quiz
end

app/models/project.rb
class Project < ApplicationRecord
  # has many
  has_many :features
  has_many :technology_groups, as: :technology_groupable, dependent: :destroy
  has_many :technologies, through: :technology_groups
  has_many :package_groups, as: :package_groupable, dependent: :destroy
  has_many :packages, through: :package_groups
  has_many :plans
  has_many :descriptions
  # validation
  validates_uniqueness_of :name
  # scopes
  scope :all_visible, -> { where(visible: true).order(:order) }

  # TODO Add packages to a project

  def to_param
    name
  end

  def completed_features
    features.where(completed: true)
  end

  def features_left_to_implement
    features.where(completed: false)
  end

  def technology_names
    technologies.map(&:name)
  end

  def package_names
    packages.map(&:name)
  end

  def theme_colour_first
    theme_colours.split(",").first
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < AdminController
    before_action :set_project, only: %i[destroy edit update].freeze
    layout "admin"

    def new
      @project = Project.new
    end

    def create
      @project = Project.new(project_params)
      if @project.save!
        flash[:success] = "Project was successfully created."
      else
        flash[:warning] = "An error occurred, please try again."
      end
      create_technology_groups
      create_package_groups
      redirect_to admin_projects_path(@project)
    end

    def destroy
      @project.destroy
      redirect_to admin_projects_path
    end

    def edit
    end

    def update
      delete_technology_groups
      create_technology_groups
      delete_package_groups
      create_package_groups
      if @project.update(project_params)
        flash[:success] = "Project was successfully updated."
      else
        flash[:warning] = "An error occurred, please try again."
      end
      redirect_to admin_projects_path(@project)
    end

    def index
      @projects = Project.all.order(:order)
    end

    private

    def delete_technology_groups
      @project.technology_groups.destroy_all
    end

    def create_technology_groups
      if params[:technologies]
        params[:technologies].each do |key, value|
          technology = Technology.find_by(name: key)
          TechnologyGroup.create(
            technology_groupable: @project,
            technology: technology
          )
        end
      end
    end

    def delete_package_groups
      @project.package_groups.destroy_all
    end

    def create_package_groups
      if params[:packages]
        params[:packages].each do |key, value|
          package = Package.find(key)
          PackageGroup.create(
            package_groupable: @project,
            package: package
          )
        end
      end
    end

    def set_project
      @project = Project.find_by(name: params[:name])
    end

    def project_params
      params.require(:project).permit(:name, :sub_title, :order, :link, :image, :description, :ux, :theme_colours, :visible)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show]

  def show
    # TODO add attribute to project visible: boolean
    @features = Feature.all
    @technologies_used = @project.technology_names
  end

  def index
    @projects = Project.all.order(:order)
  end

  private

  def set_project
    @project = Project.find_by(name: params[:name])
  end
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: [:admin, project]) do |form| %>

  <div class="form-group">
    <%= form.label :order %>
    <%= form.text_field :order, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :visible %>
    <%= form.check_box :visible, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :sub_title %>
    <%= form.text_field :sub_title, class: "form-control" %>
  </div>

  <p>#mainthemecolour, #secondarythemecolour, #other, #other</p>
  <div class="form-group">
    <%= form.label :theme_colours %>
    <%= form.text_field :theme_colours, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :logo %>
    <%= render partial: "/admin/shared/radio_image_select", locals: {file_path: "app/assets/images/logos/*", attribute: :logo, form: form} %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= render partial: "/admin/shared/radio_image_select", locals: {file_path: "app/assets/images/illustrations/*", attribute: :image, form: form} %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :ux %>
    <%= form.text_area :ux, class: "form-control" %>
  </div>

  <hr>

  <h4>Technologies</h4>

  <div class="admin-technologyOptionsContainer">
    <% Technology.all.each do |technology| %>
      <div class="form-group">
        <%= image_tag technology.icon %>
        <%= label_tag technology.name %>
        <%= check_box_tag "[technologies][#{technology.name}]", {}, project.technology_names.include?(technology.name) %>
      </div>
    <% end %>
  </div>

  <hr>

  <h4>Packages</h4>

  <div class="admin-technologyOptionsContainer">
    <% Package.all.each do |package| %>
      <div class="form-group">
        <%= label_tag package.name %>
        <%= check_box_tag "[packages][#{package.id}]", {}, project.package_names.include?(package.name) %>
      </div>
    <% end %>
  </div>

  <hr>

  <div class="actions">
  <%= form.submit class: "btn btn-success w-100 mt-3" %>
  </div>

<% end %>

app/views/admin/projects/edit.html.erb
<%= render partial: "form", locals: { project: @project } %>

app/views/admin/projects/index.html.erb
<%= link_to "New", new_admin_project_path, class: "btn btn-success" %>

<h3>Projects</h3>

<table class="table ">
  <tr>
    <td>Name</td>
    <td>Order</td>
    <td>Actions</td>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.order %></td>
      <td>
        <%= link_to "View", project_path(project), class: "btn btn-secondary" %>
        <%= link_to "Edit", edit_admin_project_path(project), class: "btn btn-info" %>
        <%= link_to "Delete", admin_project_path(project), class: "btn btn-danger", method: :delete, :data => {:confirm => 'Are you sure?', :method => "Delete"} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/projects/new.html.erb
<%= render partial: "form", locals: { project: @project } %>