config/routes.rb
Rails.application.routes.draw do
  devise_for :administrator

  namespace :admin do
    root "projects#index"

    resources :descriptions
    resources :features, param: :name
    resources :projects, param: :name
    resources :plans
    resources :packages, param: :name
    resources :technologies
    resources :technology_types
    resources :technology_types
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#home"

  get "feature/:name" => "features#show", as: :feature
  get "features" => "features#index", as: :features
  get "project/:name" => "projects#show", as: :project
  get "projects" => "projects#index", as: :projects
  get "technology/:name" => "technologies#show", as: :technology
  get "packages" => "packages#index", as: :packages
  get "dashboard" => "dashboard#dashboard", as: :dashboard
  get "booking-application-features" => 'booking_application#features', as: :booking_application_features

  # feed for learning spanish
  get "/spanish-feed" => "spanish#feed", defaults: {format: :json}

  draw :quiz
end

app/controllers/admin/technology_types_controller.rb
module Admin
  class TechnologyTypesController < AdminController
    before_action :set_technology_type, only: %i[destroy edit update].freeze
    layout "admin"

    def new
      @technology_type = TechnologyType.new
    end

    def create
      @technology_type = TechnologyType.new(technology_type_params)
      if @technology_type.save
        flash[:success] = "TechnologyType was successfully created."
        redirect_to admin_technology_types_path(@technology_type)
      else
        flash[:warning] = "An error occurred, please try again."
        render "new"
      end
    end

    def destroy
      @technology_type.destroy
      redirect_to admin_technology_types_path
    end

    def edit
    end

    def update
      if @technology_type.update(technology_type_params)
        flash[:success] = "TechnologyType was successfully updated."
      else
        flash[:warning] = "An error occurred, please try again."
      end
      redirect_to admin_technology_types_path(@technology_type)
    end

    def index
      @technology_types = TechnologyType.all
    end

    private

    def set_technology_type
      @technology_type = TechnologyType.find(params[:id])
    end

    def technology_type_params
      params.require(:technology_type).permit(:name, :description, :link, :technology_id)
    end
  end
end

app/views/admin/technology_types/_form.html.erb
<%= form_with(model: [:admin, technology_type]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success w-100 mt-3" %>
  </div>
<% end %>

app/views/admin/technology_types/edit.html.erb
<%= render partial: "form", locals: { technology_type: @technology_type } %>

app/views/admin/technology_types/index.html.erb
<%= link_to "New", new_admin_technology_type_path, class: "btn btn-success" %>

<h3>Technologies</h3>

<table class="table ">
  <tr>
    <td>Name</td>
    <td>Actions</td>
  </tr>
  <% @technology_types.each do |technology_type| %>
    <tr>
      <td>
        <%= technology_type.name %>
      </td>
      <td>
        <%= link_to "Edit", edit_admin_technology_type_path(technology_type), class: "btn btn-info" %>
        <%= link_to "Delete", admin_technology_type_path(technology_type), class: "btn btn-danger", method: :delete, :data => {:confirm => 'Are you sure?', :method => "Delete"} %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/technology_types/new.html.erb
<%= render partial: "form", locals: { technology_type: @technology_type } %>